# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import recording_pb2 as recording__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in recording_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecordingIngestStub(object):
    """KEPT IN SYNC MANUALLY with audio-ingestion/record-service/proto/recording.proto.
    Two independent deployables (agents, record-service) each generate their own
    stubs from their own copy of this file rather than sharing a package --
    see audio-ingestion/PLAN.md Phase 2 notes for why. If you change one, change
    both and regenerate (agents: scripts/gen_proto.sh, record-service: same).

    Agent -> record-service. Bidi so the server can ack/reject the session
    early (PLAN.md D5 tier 1) instead of only replying after the whole call
    has ended, which a plain client-streaming RPC would force.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamAudio = channel.stream_stream(
                '/record_service.v1.RecordingIngest/StreamAudio',
                request_serializer=recording__pb2.AudioChunk.SerializeToString,
                response_deserializer=recording__pb2.RecordingAck.FromString,
                _registered_method=True)


class RecordingIngestServicer(object):
    """KEPT IN SYNC MANUALLY with audio-ingestion/record-service/proto/recording.proto.
    Two independent deployables (agents, record-service) each generate their own
    stubs from their own copy of this file rather than sharing a package --
    see audio-ingestion/PLAN.md Phase 2 notes for why. If you change one, change
    both and regenerate (agents: scripts/gen_proto.sh, record-service: same).

    Agent -> record-service. Bidi so the server can ack/reject the session
    early (PLAN.md D5 tier 1) instead of only replying after the whole call
    has ended, which a plain client-streaming RPC would force.
    """

    def StreamAudio(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecordingIngestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamAudio': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamAudio,
                    request_deserializer=recording__pb2.AudioChunk.FromString,
                    response_serializer=recording__pb2.RecordingAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'record_service.v1.RecordingIngest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('record_service.v1.RecordingIngest', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecordingIngest(object):
    """KEPT IN SYNC MANUALLY with audio-ingestion/record-service/proto/recording.proto.
    Two independent deployables (agents, record-service) each generate their own
    stubs from their own copy of this file rather than sharing a package --
    see audio-ingestion/PLAN.md Phase 2 notes for why. If you change one, change
    both and regenerate (agents: scripts/gen_proto.sh, record-service: same).

    Agent -> record-service. Bidi so the server can ack/reject the session
    early (PLAN.md D5 tier 1) instead of only replying after the whole call
    has ended, which a plain client-streaming RPC would force.
    """

    @staticmethod
    def StreamAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/record_service.v1.RecordingIngest/StreamAudio',
            recording__pb2.AudioChunk.SerializeToString,
            recording__pb2.RecordingAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
