// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.2
// source: proto/recording.proto

package recordpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecordingIngest_StreamAudio_FullMethodName = "/record_service.v1.RecordingIngest/StreamAudio"
)

// RecordingIngestClient is the client API for RecordingIngest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Agent -> record-service. Bidi so the server can ack/reject the session
// early (PLAN.md D5 tier 1) instead of only replying after the whole call
// has ended, which a plain client-streaming RPC would force.
type RecordingIngestClient interface {
	StreamAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, RecordingAck], error)
}

type recordingIngestClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordingIngestClient(cc grpc.ClientConnInterface) RecordingIngestClient {
	return &recordingIngestClient{cc}
}

func (c *recordingIngestClient) StreamAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, RecordingAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RecordingIngest_ServiceDesc.Streams[0], RecordingIngest_StreamAudio_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AudioChunk, RecordingAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RecordingIngest_StreamAudioClient = grpc.BidiStreamingClient[AudioChunk, RecordingAck]

// RecordingIngestServer is the server API for RecordingIngest service.
// All implementations must embed UnimplementedRecordingIngestServer
// for forward compatibility.
//
// Agent -> record-service. Bidi so the server can ack/reject the session
// early (PLAN.md D5 tier 1) instead of only replying after the whole call
// has ended, which a plain client-streaming RPC would force.
type RecordingIngestServer interface {
	StreamAudio(grpc.BidiStreamingServer[AudioChunk, RecordingAck]) error
	mustEmbedUnimplementedRecordingIngestServer()
}

// UnimplementedRecordingIngestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecordingIngestServer struct{}

func (UnimplementedRecordingIngestServer) StreamAudio(grpc.BidiStreamingServer[AudioChunk, RecordingAck]) error {
	return status.Error(codes.Unimplemented, "method StreamAudio not implemented")
}
func (UnimplementedRecordingIngestServer) mustEmbedUnimplementedRecordingIngestServer() {}
func (UnimplementedRecordingIngestServer) testEmbeddedByValue()                         {}

// UnsafeRecordingIngestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordingIngestServer will
// result in compilation errors.
type UnsafeRecordingIngestServer interface {
	mustEmbedUnimplementedRecordingIngestServer()
}

func RegisterRecordingIngestServer(s grpc.ServiceRegistrar, srv RecordingIngestServer) {
	// If the following call panics, it indicates UnimplementedRecordingIngestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecordingIngest_ServiceDesc, srv)
}

func _RecordingIngest_StreamAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RecordingIngestServer).StreamAudio(&grpc.GenericServerStream[AudioChunk, RecordingAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RecordingIngest_StreamAudioServer = grpc.BidiStreamingServer[AudioChunk, RecordingAck]

// RecordingIngest_ServiceDesc is the grpc.ServiceDesc for RecordingIngest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecordingIngest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "record_service.v1.RecordingIngest",
	HandlerType: (*RecordingIngestServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAudio",
			Handler:       _RecordingIngest_StreamAudio_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/recording.proto",
}
