// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: proto/recording.proto

package recordpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AudioChunk_Start
	//	*AudioChunk_Pcm
	//	*AudioChunk_Dropped
	Payload       isAudioChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_proto_recording_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recording_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_proto_recording_proto_rawDescGZIP(), []int{0}
}

func (x *AudioChunk) GetPayload() isAudioChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AudioChunk) GetStart() *SessionStart {
	if x != nil {
		if x, ok := x.Payload.(*AudioChunk_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *AudioChunk) GetPcm() []byte {
	if x != nil {
		if x, ok := x.Payload.(*AudioChunk_Pcm); ok {
			return x.Pcm
		}
	}
	return nil
}

func (x *AudioChunk) GetDropped() *DroppedFrames {
	if x != nil {
		if x, ok := x.Payload.(*AudioChunk_Dropped); ok {
			return x.Dropped
		}
	}
	return nil
}

type isAudioChunk_Payload interface {
	isAudioChunk_Payload()
}

type AudioChunk_Start struct {
	Start *SessionStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type AudioChunk_Pcm struct {
	Pcm []byte `protobuf:"bytes,2,opt,name=pcm,proto3,oneof"`
}

type AudioChunk_Dropped struct {
	Dropped *DroppedFrames `protobuf:"bytes,3,opt,name=dropped,proto3,oneof"`
}

func (*AudioChunk_Start) isAudioChunk_Payload() {}

func (*AudioChunk_Pcm) isAudioChunk_Payload() {}

func (*AudioChunk_Dropped) isAudioChunk_Payload() {}

// First message of a stream. Doubles as the (re)connect handshake for
// PLAN.md D5 tier 2 -- sending this again with the same room_id/track_id
// within the grace period resumes the existing session instead of opening
// a new upload.
type SessionStart struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RoomId              string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TrackId             string                 `protobuf:"bytes,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	ParticipantIdentity string                 `protobuf:"bytes,3,opt,name=participant_identity,json=participantIdentity,proto3" json:"participant_identity,omitempty"`
	Source              string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"` // "mic" | "screen"
	SampleRate          int32                  `protobuf:"varint,5,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Channels            int32                  `protobuf:"varint,6,opt,name=channels,proto3" json:"channels,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SessionStart) Reset() {
	*x = SessionStart{}
	mi := &file_proto_recording_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStart) ProtoMessage() {}

func (x *SessionStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recording_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStart.ProtoReflect.Descriptor instead.
func (*SessionStart) Descriptor() ([]byte, []int) {
	return file_proto_recording_proto_rawDescGZIP(), []int{1}
}

func (x *SessionStart) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SessionStart) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *SessionStart) GetParticipantIdentity() string {
	if x != nil {
		return x.ParticipantIdentity
	}
	return ""
}

func (x *SessionStart) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SessionStart) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *SessionStart) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

// Agent-side backpressure drop count (PLAN.md D12) -- record-service only
// annotates on this, it never discards data or acts on it unilaterally.
type DroppedFrames struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DroppedFrames) Reset() {
	*x = DroppedFrames{}
	mi := &file_proto_recording_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DroppedFrames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DroppedFrames) ProtoMessage() {}

func (x *DroppedFrames) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recording_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DroppedFrames.ProtoReflect.Descriptor instead.
func (*DroppedFrames) Descriptor() ([]byte, []int) {
	return file_proto_recording_proto_rawDescGZIP(), []int{2}
}

func (x *DroppedFrames) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RecordingAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // accepted | rejected | completed
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordingAck) Reset() {
	*x = RecordingAck{}
	mi := &file_proto_recording_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordingAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordingAck) ProtoMessage() {}

func (x *RecordingAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recording_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordingAck.ProtoReflect.Descriptor instead.
func (*RecordingAck) Descriptor() ([]byte, []int) {
	return file_proto_recording_proto_rawDescGZIP(), []int{3}
}

func (x *RecordingAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RecordingAck) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *RecordingAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_recording_proto protoreflect.FileDescriptor

const file_proto_recording_proto_rawDesc = "" +
	"\n" +
	"\x15proto/recording.proto\x12\x11record_service.v1\"\xa2\x01\n" +
	"\n" +
	"AudioChunk\x127\n" +
	"\x05start\x18\x01 \x01(\v2\x1f.record_service.v1.SessionStartH\x00R\x05start\x12\x12\n" +
	"\x03pcm\x18\x02 \x01(\fH\x00R\x03pcm\x12<\n" +
	"\adropped\x18\x03 \x01(\v2 .record_service.v1.DroppedFramesH\x00R\adroppedB\t\n" +
	"\apayload\"\xca\x01\n" +
	"\fSessionStart\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x19\n" +
	"\btrack_id\x18\x02 \x01(\tR\atrackId\x121\n" +
	"\x14participant_identity\x18\x03 \x01(\tR\x13participantIdentity\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1f\n" +
	"\vsample_rate\x18\x05 \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x06 \x01(\x05R\bchannels\"%\n" +
	"\rDroppedFrames\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"[\n" +
	"\fRecordingAck\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2d\n" +
	"\x0fRecordingIngest\x12Q\n" +
	"\vStreamAudio\x12\x1d.record_service.v1.AudioChunk\x1a\x1f.record_service.v1.RecordingAck(\x010\x01BDZBgithub.com/mezonai/mezon-call-translation/agents/internal/recordpbb\x06proto3"

var (
	file_proto_recording_proto_rawDescOnce sync.Once
	file_proto_recording_proto_rawDescData []byte
)

func file_proto_recording_proto_rawDescGZIP() []byte {
	file_proto_recording_proto_rawDescOnce.Do(func() {
		file_proto_recording_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_recording_proto_rawDesc), len(file_proto_recording_proto_rawDesc)))
	})
	return file_proto_recording_proto_rawDescData
}

var file_proto_recording_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_recording_proto_goTypes = []any{
	(*AudioChunk)(nil),    // 0: record_service.v1.AudioChunk
	(*SessionStart)(nil),  // 1: record_service.v1.SessionStart
	(*DroppedFrames)(nil), // 2: record_service.v1.DroppedFrames
	(*RecordingAck)(nil),  // 3: record_service.v1.RecordingAck
}
var file_proto_recording_proto_depIdxs = []int32{
	1, // 0: record_service.v1.AudioChunk.start:type_name -> record_service.v1.SessionStart
	2, // 1: record_service.v1.AudioChunk.dropped:type_name -> record_service.v1.DroppedFrames
	0, // 2: record_service.v1.RecordingIngest.StreamAudio:input_type -> record_service.v1.AudioChunk
	3, // 3: record_service.v1.RecordingIngest.StreamAudio:output_type -> record_service.v1.RecordingAck
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_recording_proto_init() }
func file_proto_recording_proto_init() {
	if File_proto_recording_proto != nil {
		return
	}
	file_proto_recording_proto_msgTypes[0].OneofWrappers = []any{
		(*AudioChunk_Start)(nil),
		(*AudioChunk_Pcm)(nil),
		(*AudioChunk_Dropped)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_recording_proto_rawDesc), len(file_proto_recording_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_recording_proto_goTypes,
		DependencyIndexes: file_proto_recording_proto_depIdxs,
		MessageInfos:      file_proto_recording_proto_msgTypes,
	}.Build()
	File_proto_recording_proto = out.File
	file_proto_recording_proto_goTypes = nil
	file_proto_recording_proto_depIdxs = nil
}
