name: Update LiveKit Env

on:
  push:
    branches:
      - dev

jobs:
  update-env:
    runs-on: livekit_agents

    steps:
      - name: Update env and restart agent
        run: |
            cd /home/nccsoft/projects/mezon-call-translation/Architect_MultiClient_Server/agents

            # Backup .env
            cp .env .envbackup

            update_env() {
              local key=$1
              local val=$2
              local escaped_val
              escaped_val=$(printf '%s\n' "$val" | sed 's/[&|]/\\&/g')

              if grep -q "^${key}=" .env; then
                sed -i.bak "s|^${key}=.*|${key}=${escaped_val}|" .env
                rm -f .env.bak
              else
                echo "${key}=${val}" >> .env
              fi
            }

            update_env "LIVEKIT_API_KEY" "${{ secrets.LIVEKIT_API_KEY }}"
            update_env "LIVEKIT_API_SECRET" "${{ secrets.LIVEKIT_API_SECRET }}"
            update_env "LIVEKIT_URL" "${{ secrets.LIVEKIT_URL }}"

            sudo systemctl restart livekit_agents.service